name: Automate GRU Form Filling

on:
  workflow_dispatch:
    inputs:
      data:
        description: 'Data for GRU automation'
        required: true
        default: '{}'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        sudo apt-get install -y python3-pip
        sudo python3 -m pip install --upgrade pip
        sudo pip3 install selenium webdriver-manager

    - name: Download and setup Chrome WebDriver
      run: |
        sudo wget -q "https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip"
        sudo unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Verify Chrome WebDriver installation
      run: sudo /usr/local/bin/chromedriver --version

    - name: Run automation script
      env:
        DATA: ${{ github.event.inputs.data }}
      run: |
        echo "$DATA" > data.json
        sudo python3 automate_gru.py "$(cat data.json)"

    - name: Check for errors
      run: sudo dmesg | grep -i error
